spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank accounts QA Rest API"
  contactDetails:
    name: "Sarah Jackson - QA Lead"
    email: "sarah.jackson@eazybank.com"
  onCallSupport:
    - (123) 456-5885
    - (123) 4565-7895