spring:
  application:
    name: "configserver"
  profiles:
    #    active: native         #This is for local use
    active: git
  cloud:
    bus:
      enabled: false
    config:
      server:
          #        native:
          #          #search-locations: "file:///D://Projects//SpringBoot Projects//config"
          #          search-locations: "classpath:/config"
        git:
          uri: "https://github.com/ArifBashaK08/EazyBank-Configs.git"
          default-label: main
          timeout: 5
          clone-on-start: true      # Clone the repo during start-up of config server
          force-pull: true      # To avoid conflicts if any changes made

encrypt:
  key: "@|)rqX1yO?x9l8yU@428cO^2VhqZ%KO"

server:
  port: 8071

#Acctuator related properties
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enable: true
    liveness-state:
      enable: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}