server:
  port: 9000

spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdb3
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
    profiles:
      activate:
        - "prod"

build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank accounts Dev Rest API"
  contactDetails:
    name: "Allen Sung - Dev Lead"
    email: "allen.sung@eazybank.com"
  onCallSupport:
    - (321) 858-1496
    - (321) 858-1495