spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards QA Rest API"
  contactDetails:
    name: "Adrian Aloe - QA Lead"
    email: "adrian.aloe@eazybank.com"
  onCallSupport:
    - (321) 989-0896
    - (321) 989-0895