server:
  port: 8090

spring:
  application:
    name: loans
  datasource:
    url: jdbc:h2:mem:testdb2
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enable: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
    profiles:
      activate:
        - "prod"

build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans Dev Rest API"
  contactDetails:
    name: "Jinoo Sung Woo - Dev Lead"
    email: "jinoo.sung.woo@eazybank.com"
  onCallSupport:
    - (852) 741-0391
    - (852) 741-0392