spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans QA Rest API"
  contactDetails:
    name: "M. D. Luffy - QA Lead"
    email: "m.d.luffy@eazybank.com"
  onCallSupport:
    - (852) 741-0491
    - (852) 741-0492